version: '3.7'

services:

  web:
    container_name: 'aspnetcore'
    image: dotnet/aspnet
    build:
      context: .
      dockerfile: AA.API/aspnetcore.dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'mypostgres'
    image: postgres:12.1-alpine
    environment:
        POSTGRES_DB: analytics
        POSTGRES_USER: aa_admin
        POSTGRES_PASSWORD: 95nJJara@x~Bs
    ports: 
        - "65432:5432"
    volumes: 
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
        - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge
